coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

flags:
  flaskapi:
    paths:
      - flaskapi/src/
  node:
    paths:
      - node/src/
  e2e:
    paths:
      - node/src/
