services:
  mmux-vite-backend:
    image: simcore/services/dynamic/mmux-vite-backend:1.6.1
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      - OSPARC_API_BASE_URL=${OSPARC_API_BASE_URL}
      - OSPARC_API_KEY=${OSPARC_API_KEY}
      - OSPARC_API_SECRET=${OSPARC_API_SECRET}
      - LOG_LEVEL=DEBUG
      - DEVELOPMENT_MODE=true
      - SERVICE_MODE=${SERVICE_MODE}
      - PERMISSIONS=${PERMISSIONS}
      - DEPLOYMENT_MODE=${DEPLOYMENT_MODE}
    volumes:
      - ./flaskapi:/app
      - ./validation/text-files:/text-files
  mmux-vite-web:
    image: simcore/services/dynamic/mmux-vite-web:1.6.1
    working_dir: /app
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./node:/app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 8080"
    environment:
      - NODE_ENV=development
      - APP_PORT=${APP_PORT:-8888}
  mmux-vite-app:
    image: simcore/services/dynamic/${APP_IMAGE}:1.6.1
    environment:
      - WEB_SERVICE=mmux-vite-web:8080
      - BACKEND_SERVICE=mmux-vite-backend:5000
    ports:
      - "${APP_PORT:-8888}:8888"
    depends_on:
      mmux-vite-backend:
        condition: service_healthy
      mmux-vite-web:
        condition: service_healthy
