"""
Regression test for SPEC.md B4/V3: local-dev compose files must gate the
Caddy proxy (`mmux-vite-app`) on `condition: service_healthy` for both
upstream services, not just container start, or it serves traffic before
`mmux-vite-backend`/`mmux-vite-web` pass their HEALTHCHECK
(30s interval, 20s start-period) — producing transient
"no upstreams available" 503s on every local stack (re)start.
"""

import os
import subprocess
from pathlib import Path
from shutil import which

import pytest

pytestmark = pytest.mark.unit

REPO_ROOT = Path(__file__).resolve().parents[2]

# docker-compose.yml is regenerated by `ooil compose` (SPEC.md V7) and already
# emits `condition: service_healthy` for these upstreams; only the
# hand-maintained dev-convenience files can drift.
COMPOSE_FILES = [
    "docker-compose-development.yml",
    "docker-compose-local.yml",
]

VITE_CONFIG = REPO_ROOT / "node" / "vite.config.ts"
RESOLVE_APP_PORT = REPO_ROOT / "scripts" / "resolve-app-port.sh"
BACKEND_ENTRYPOINT = REPO_ROOT / "flaskapi" / "entrypoint.sh"


def test_app_service_depends_on_healthy_upstreams():
    for filename in COMPOSE_FILES:
        content = (REPO_ROOT / filename).read_text()

        depends_on_idx = content.index("depends_on:")
        depends_on_block = content[depends_on_idx : depends_on_idx + 200]

        assert "mmux-vite-backend" in depends_on_block, (
            f"{filename}: mmux-vite-app depends_on must list mmux-vite-backend"
        )
        assert "mmux-vite-web" in depends_on_block, (
            f"{filename}: mmux-vite-app depends_on must list mmux-vite-web"
        )
        assert depends_on_block.count("condition: service_healthy") == 2, (
            f"{filename}: mmux-vite-app depends_on must use "
            "`condition: service_healthy` for both mmux-vite-backend and "
            "mmux-vite-web (V3) — plain list-form depends_on only waits for "
            "container start, not health (B4)"
        )


def test_vite_dev_server_does_not_force_internal_origin():
    content = VITE_CONFIG.read_text()

    assert "origin:" not in content, (
        "node/vite.config.ts: Vite dev server must derive its browser origin "
        "from the request host so docker-compose APP_PORT fallback ports keep "
        "serving dev assets/HMR through Caddy (V17/B5)"
    )
    assert "clientPort: appPort" in content, (
        "node/vite.config.ts: Vite HMR must use APP_PORT as the browser-facing "
        "client port instead of the internal 8080 dev-server port (V17/B5)"
    )


def test_development_compose_passes_app_port_to_vite():
    content = (REPO_ROOT / "docker-compose-development.yml").read_text()

    assert "APP_PORT=${APP_PORT:-8888}" in content, (
        "docker-compose-development.yml: mmux-vite-web must receive APP_PORT "
        "so Vite can advertise the same browser-facing port printed by the "
        "Makefile fallback logic (V17/B5)"
    )


def test_development_backend_uses_writable_uv_cache():
    content = (REPO_ROOT / "docker-compose-development.yml").read_text()

    # Scope to the mmux-vite-backend service block: a bare substring check on the
    # whole file is also satisfied by mmux-vite-web's identical user/`UV_CACHE_DIR`
    # lines, which previously masked the backend running as root (PR #647 review).
    backend_idx = content.index("mmux-vite-backend:")
    web_idx = content.index("mmux-vite-web:")
    backend_block = content[backend_idx:web_idx]

    assert 'user: "${HOST_UID:-1000}:${HOST_GID:-1000}"' in backend_block, (
        "docker-compose-development.yml: mmux-vite-backend must run as the host UID/GID "
        "from container start, not root (V31vr)"
    )
    cache_line = next(line for line in backend_block.splitlines() if "UV_CACHE_DIR=" in line)
    cache_dir = cache_line.split("UV_CACHE_DIR=", 1)[1].strip()
    assert cache_dir, (
        "docker-compose-development.yml: non-root mmux-vite-backend must direct uv's "
        "cache away from its unwritable default /.cache/uv (V36zn/B22zn)"
    )
    assert not cache_dir.startswith("/app"), (
        "docker-compose-development.yml: UV_CACHE_DIR must live OUTSIDE the "
        "./flaskapi:/app bind mount. A host-backed cache is not root-proof: one "
        "root-era write to it (e.g. the old /app/.cache/uv, seeded root-owned on "
        "the host) permanently breaks every later uid-1000 `uv run` at container "
        "start with 'Permission denied' → exit 2 (V39jx/B25jx)"
    )


def test_development_compose_user_pin_is_launcher_supplied():
    """V31vr/B24kp: the `user:` pin only holds if the HOST_UID/HOST_GID it
    interpolates are ACTUALLY supplied. Shell-builtin UID/GID never survive
    make + /bin/sh, so plain-UID pins silently degrade to 1000:1000 on
    non-1000 hosts while every placeholder-text assertion still passes."""
    content = (REPO_ROOT / "docker-compose-development.yml").read_text()
    makefile_content = (REPO_ROOT / "Makefile").read_text()

    # both bind-mounting services pin the launcher-provided identity
    assert content.count('user: "${HOST_UID:-1000}:${HOST_GID:-1000}"') == 2
    assert "${UID:" not in content and "${GID:" not in content, (
        "docker-compose-development.yml: UID/GID shell builtins are not exported "
        "through make + /bin/sh (B24kp); use HOST_UID/HOST_GID instead"
    )

    # every development launch passes the real host identity through
    launch = "docker compose --file docker-compose-development.yml up"
    total = makefile_content.count(launch)
    guarded = makefile_content.count(f"$(HOST_ID_ENV) {launch}")
    assert total > 0
    assert guarded == total, (
        "Makefile: every docker-compose-development.yml launcher must be prefixed with "
        "$(HOST_ID_ENV) so compose receives the real host UID/GID (V31vr/B24kp)"
    )
    assert "HOST_UID=$$(id -u)" in makefile_content
    assert "HOST_GID=$$(id -g)" in makefile_content


def test_development_backend_and_web_never_run_as_root():
    """Regression test: PR #613 briefly ran mmux-vite-backend as root (`user: "0:0"`)
    with an entrypoint chown+gosu dance to drop privileges, which self-inflicted the
    root-owned persistence-mount bug it was meant to fix. Both dev services must run
    as the host UID/GID from container start (V31vr); no root, chown, or gosu.
    """
    compose_content = (REPO_ROOT / "docker-compose-development.yml").read_text()
    entrypoint_content = BACKEND_ENTRYPOINT.read_text()
    dockerfile_content = (REPO_ROOT / "flaskapi" / "Dockerfile").read_text()

    assert 'user: "0:0"' not in compose_content
    assert "gosu" not in entrypoint_content
    assert "chown" not in entrypoint_content
    assert "gosu" not in dockerfile_content


def test_development_web_uses_production_image_with_runtime_install():
    """Regression test: PR #613 introduced a second local-only image
    (`mmux-vite-web-dev`, builder stage) with a prebuilt node_modules volume to
    dodge a transient npm-install network failure. That never shipped as a real
    oSPARC service and added chown/volume complexity for no lasting benefit —
    dev must reuse the single published `mmux-vite-web` image and install at
    container start, per the colleague's original design.
    """
    compose_content = (REPO_ROOT / "docker-compose-development.yml").read_text()
    makefile_content = (REPO_ROOT / "Makefile").read_text()
    dockerfile_content = (REPO_ROOT / "node" / "Dockerfile").read_text()

    assert "image: simcore/services/dynamic/mmux-vite-web:1.6.1" in compose_content
    assert "mmux-vite-web-dev" not in compose_content
    assert "mmux-vite-web-node-modules" not in compose_content
    assert (
        'command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 8080"'
        in compose_content
    )
    assert "mmux-vite-web-dev" not in makefile_content
    assert "APP_UID" not in dockerfile_content
    assert "APP_GID" not in dockerfile_content
    assert "chown" not in dockerfile_content


def test_development_backend_no_venv_volume_plain_uv_run():
    """Regression test: PR #613 preserved the image-built /app/.venv in a named
    volume + `uv run --no-sync` to skip resyncing on every start; the volume was
    seeded root-owned by the image build, requiring the root/gosu/chown dance
    reverted above. Dev backend runs `uv run` (resyncing at every start) with no
    preserved venv volume, matching the colleague's original design.
    """
    compose_content = (REPO_ROOT / "docker-compose-development.yml").read_text()
    entrypoint_content = BACKEND_ENTRYPOINT.read_text()

    assert "mmux-vite-backend-venv" not in compose_content
    assert "exec uv run python -m flask run" in entrypoint_content
    assert "--no-sync" not in entrypoint_content


def test_make_targets_reuse_running_compose_app_port():
    content = (REPO_ROOT / "Makefile").read_text()

    assert "scripts/find-free-port.sh 8888" not in content, (
        "Make run targets must not blindly recalculate a fresh free port while "
        "the Compose app service may already be running on a different port (V19/B7)"
    )
    assert content.count("scripts/resolve-app-port.sh docker-compose-development.yml 8888") == 6
    assert content.count("scripts/resolve-app-port.sh docker-compose-local.yml 8888") == 6
    assert content.count("MMUX app URL (this WSL shell): http://localhost:%s") == 12
    assert content.count("MMUX app URL (Windows browser via WSL IP): http://%s:%s") == 12
    assert "hostname -I | awk '{print $$1}'" in content
    assert content.count("============================================================") == 24


def test_resolve_app_port_prefers_existing_compose_publication(tmp_path):
    fake_bin = tmp_path / "bin"
    fake_bin.mkdir()
    docker = fake_bin / "docker"
    docker.write_text(
        "#!/usr/bin/env bash\n"
        'if [[ "$*" == "compose --file docker-compose-development.yml port mmux-vite-app 8888" ]]; then\n'
        "  echo '0.0.0.0:8891'\n"
        "  exit 0\n"
        "fi\n"
        "exit 1\n"
    )
    docker.chmod(0o755)

    env = os.environ.copy()
    env["PATH"] = f"{fake_bin}:{env['PATH']}"

    result = subprocess.run(
        ["bash", str(RESOLVE_APP_PORT), "docker-compose-development.yml", "8888"],
        cwd=REPO_ROOT,
        env=env,
        check=True,
        capture_output=True,
        text=True,
    )

    assert result.stdout.strip() == "8891"


def test_resolve_app_port_finds_sibling_script_when_invoked_from_other_cwd(tmp_path):
    """Regression test for SPEC.md B9/V22: resolve-app-port.sh called its
    find-free-port.sh fallback via a cwd-relative path (`scripts/find-free-port.sh`),
    so invoking it from anywhere other than the repo root failed instead of
    falling back to a freshly-scanned free port.
    """
    fake_bin = tmp_path / "bin"
    fake_bin.mkdir()
    docker = fake_bin / "docker"
    # No existing Compose publication -> script must fall back to find-free-port.sh.
    docker.write_text("#!/usr/bin/env bash\nexit 1\n")
    docker.chmod(0o755)

    env = os.environ.copy()
    env["PATH"] = f"{fake_bin}:{env['PATH']}"

    other_cwd = tmp_path / "elsewhere"
    other_cwd.mkdir()

    result = subprocess.run(
        ["bash", str(RESOLVE_APP_PORT), "docker-compose-development.yml", "8888"],
        cwd=other_cwd,
        env=env,
        capture_output=True,
        text=True,
    )

    assert result.returncode == 0, result.stderr
    assert result.stdout.strip().isdigit()


def test_find_free_port_fails_fast_without_timeout_command(tmp_path):
    """Regression test for SPEC.md B10/V23: find-free-port.sh used
    `if ! timeout ...` to probe a port; if the `timeout` command itself is
    missing, that condition is always true, so the script incorrectly reports
    the very first port scanned as free.
    """
    fake_bin = tmp_path / "bin"
    fake_bin.mkdir()
    # Provide bash on PATH, but deliberately omit `timeout`.
    real_bash = which("bash")
    assert real_bash is not None, "bash must be available to run this test"
    (fake_bin / "bash").symlink_to(real_bash)

    env = os.environ.copy()
    env["PATH"] = str(fake_bin)

    result = subprocess.run(
        ["bash", str(REPO_ROOT / "scripts" / "find-free-port.sh"), "8888"],
        env=env,
        capture_output=True,
        text=True,
    )

    assert result.returncode != 0
    assert "timeout" in result.stderr.lower()
