"""
Regression test for SPEC.md B4/V3: local-dev compose files must gate the
Caddy proxy (`mmux-vite-app`) on `condition: service_healthy` for both
upstream services, not just container start, or it serves traffic before
`mmux-vite-backend`/`mmux-vite-web` pass their HEALTHCHECK
(30s interval, 20s start-period) — producing transient
"no upstreams available" 503s on every local stack (re)start.
"""

import os
import subprocess
from pathlib import Path
from shutil import which

import pytest

pytestmark = pytest.mark.unit

REPO_ROOT = Path(__file__).resolve().parents[2]

# docker-compose.yml is regenerated by `ooil compose` (SPEC.md V7) and already
# emits `condition: service_healthy` for these upstreams; only the
# hand-maintained dev-convenience files can drift.
COMPOSE_FILES = [
    "docker-compose-development.yml",
    "docker-compose-local.yml",
]

VITE_CONFIG = REPO_ROOT / "node" / "vite.config.ts"
RESOLVE_APP_PORT = REPO_ROOT / "scripts" / "resolve-app-port.sh"


def test_app_service_depends_on_healthy_upstreams():
    for filename in COMPOSE_FILES:
        content = (REPO_ROOT / filename).read_text()

        depends_on_idx = content.index("depends_on:")
        depends_on_block = content[depends_on_idx : depends_on_idx + 200]

        assert "mmux-vite-backend" in depends_on_block, (
            f"{filename}: mmux-vite-app depends_on must list mmux-vite-backend"
        )
        assert "mmux-vite-web" in depends_on_block, (
            f"{filename}: mmux-vite-app depends_on must list mmux-vite-web"
        )
        assert depends_on_block.count("condition: service_healthy") == 2, (
            f"{filename}: mmux-vite-app depends_on must use "
            "`condition: service_healthy` for both mmux-vite-backend and "
            "mmux-vite-web (V3) — plain list-form depends_on only waits for "
            "container start, not health (B4)"
        )


def test_vite_dev_server_does_not_force_internal_origin():
    content = VITE_CONFIG.read_text()

    assert "origin:" not in content, (
        "node/vite.config.ts: Vite dev server must derive its browser origin "
        "from the request host so docker-compose APP_PORT fallback ports keep "
        "serving dev assets/HMR through Caddy (V17/B5)"
    )
    assert "clientPort: appPort" in content, (
        "node/vite.config.ts: Vite HMR must use APP_PORT as the browser-facing "
        "client port instead of the internal 8080 dev-server port (V17/B5)"
    )


def test_development_compose_passes_app_port_to_vite():
    content = (REPO_ROOT / "docker-compose-development.yml").read_text()

    assert "APP_PORT=${APP_PORT:-8888}" in content, (
        "docker-compose-development.yml: mmux-vite-web must receive APP_PORT "
        "so Vite can advertise the same browser-facing port printed by the "
        "Makefile fallback logic (V17/B5)"
    )


def test_make_targets_reuse_running_compose_app_port():
    content = (REPO_ROOT / "Makefile").read_text()

    assert "scripts/find-free-port.sh 8888" not in content, (
        "Make run targets must not blindly recalculate a fresh free port while "
        "the Compose app service may already be running on a different port (V19/B7)"
    )
    assert content.count("scripts/resolve-app-port.sh docker-compose-development.yml 8888") == 6
    assert content.count("scripts/resolve-app-port.sh docker-compose-local.yml 8888") == 6
    assert content.count("MMUX app URL (this WSL shell): http://localhost:%s") == 12
    assert content.count("MMUX app URL (Windows browser via WSL IP): http://%s:%s") == 12
    assert "hostname -I | awk '{print $$1}'" in content
    assert content.count("============================================================") == 24


def test_resolve_app_port_prefers_existing_compose_publication(tmp_path):
    fake_bin = tmp_path / "bin"
    fake_bin.mkdir()
    docker = fake_bin / "docker"
    docker.write_text(
        "#!/usr/bin/env bash\n"
        'if [[ "$*" == "compose --file docker-compose-development.yml port mmux-vite-app 8888" ]]; then\n'
        "  echo '0.0.0.0:8891'\n"
        "  exit 0\n"
        "fi\n"
        "exit 1\n"
    )
    docker.chmod(0o755)

    env = os.environ.copy()
    env["PATH"] = f"{fake_bin}:{env['PATH']}"

    result = subprocess.run(
        ["bash", str(RESOLVE_APP_PORT), "docker-compose-development.yml", "8888"],
        cwd=REPO_ROOT,
        env=env,
        check=True,
        capture_output=True,
        text=True,
    )

    assert result.stdout.strip() == "8891"


def test_resolve_app_port_finds_sibling_script_when_invoked_from_other_cwd(tmp_path):
    """Regression test for SPEC.md B9/V22: resolve-app-port.sh called its
    find-free-port.sh fallback via a cwd-relative path (`scripts/find-free-port.sh`),
    so invoking it from anywhere other than the repo root failed instead of
    falling back to a freshly-scanned free port.
    """
    fake_bin = tmp_path / "bin"
    fake_bin.mkdir()
    docker = fake_bin / "docker"
    # No existing Compose publication -> script must fall back to find-free-port.sh.
    docker.write_text("#!/usr/bin/env bash\nexit 1\n")
    docker.chmod(0o755)

    env = os.environ.copy()
    env["PATH"] = f"{fake_bin}:{env['PATH']}"

    other_cwd = tmp_path / "elsewhere"
    other_cwd.mkdir()

    result = subprocess.run(
        ["bash", str(RESOLVE_APP_PORT), "docker-compose-development.yml", "8888"],
        cwd=other_cwd,
        env=env,
        capture_output=True,
        text=True,
    )

    assert result.returncode == 0, result.stderr
    assert result.stdout.strip().isdigit()


def test_find_free_port_fails_fast_without_timeout_command(tmp_path):
    """Regression test for SPEC.md B10/V23: find-free-port.sh used
    `if ! timeout ...` to probe a port; if the `timeout` command itself is
    missing, that condition is always true, so the script incorrectly reports
    the very first port scanned as free.
    """
    fake_bin = tmp_path / "bin"
    fake_bin.mkdir()
    # Provide bash on PATH, but deliberately omit `timeout`.
    real_bash = which("bash")
    assert real_bash is not None, "bash must be available to run this test"
    (fake_bin / "bash").symlink_to(real_bash)

    env = os.environ.copy()
    env["PATH"] = str(fake_bin)

    result = subprocess.run(
        ["bash", str(REPO_ROOT / "scripts" / "find-free-port.sh"), "8888"],
        env=env,
        capture_output=True,
        text=True,
    )

    assert result.returncode != 0
    assert "timeout" in result.stderr.lower()
